name: jigle
description: "SL JIG management application"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/jigle_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/jigle_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/maps/
    - assets/sample_box1.png
    - assets/bdong_map.png
    - assets/shelf_L1.png
    - assets/shelf_R1.png
    - assets/shelf_C1.png
    - assets/sl_logo.png
    - assets/jigle_logo.png   # ← 로고 파일 등록

  fonts:
    - family: Pretendard-M
      fonts:
        - asset: fonts/Pretendard-Medium.otf
