name: jigle
description: "SL JIG management application"
publish_to: 'none' # private package, not for pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/maps/
    - assets/sample_box1.png
    - assets/bdong_map.png
    - assets/shelf_L1.png
    - assets/shelf_R1.png
    - assets/shelf_C1.png
    - assets/sl_logo.png
  fonts:
    - family: Pretendard-M
      fonts:
        - asset: fonts/Pretendard-Medium.otf

